
# Communciation Types {#sec-comm-types}

<!---
https://learning.oreilly.com/library/view/the-art-and/9780470247594/pr04.html
--->


## Intrapersonal

## Nonverbal

<!---
From https://online.utpb.edu/about-us/articles/communication/how-much-of-communication-is-nonverbal/
--->

The 55/38/7 Formula
-------------------------

The 90% figure wasn’t plucked out of thin air. It was Albert Mehrabian, a researcher 
of body language, who first broke down the components of a face-to-face conversation. 
He found that communication is 55% nonverbal, 38% vocal, and 7% words only. This is 
where the idea that the vast majority of communication is nonverbal originated, but 
does this really mean that less than 10% of information is conveyed in spoken words?

It turns out that the above formula was developed with a specific purpose in mind:
comparing facial and vocal components to decipher a person’s attitude. According to 
Mehrabian, 

:::{.quote}
When there are inconsistencies between attitudes communicated verbally and posturally, 
the postural component should dominate in determining the total attitude that is inferred.
:::

The communication happened in a situation where verbal and non-verbal channels
were **inconsistent**. In that case, non-verbal communication is more important.
If someone writhes in agony on the ground with an open fracture, a bone sticking
out, and yells "I am OK!", we believe the non-verbal cues of a person in pain
and not the spoken words. They are **not** OK.

In normal situations, where the verbal and non-verbal channels are aligned, 
non-verbal communication is not the most important channel. Otherwise we would 
not be able to comprehend the Gettysburg address by reading. But non-verbal 
communication is a very important channel. In a face-to-face conversation, body 
language and facial expressions have a remarkable impact on how information is 
interpreted and retained.

In “The Definitive Book of Body Language,” Allan and Barbara Pease analyzed thousands 
of recorded sales negotiations from the 1970s and 1980s and found that body language 
accounted for the majority of the impact made negotiating. They also considered how 
the person with the strongest argument usually wins in negotiations over the phone
but not always in face-to-face conversations. Although the idea that 90% of 
communication is nonverbal can be put to rest, a person’s body language and our 
first impression of them can heavily influence our decision-making.

The Power of Body Language
-------------------------
Now that we know that we know the important role nonverbal signals play in communication, how can we use body language and tone to communicate more effectively? Perhaps more importantly, how can we prevent nonverbal forms of communication from falsely influencing our perceptions of others?

Making a Good First Impression
-------------------------
If you’re interested in a communications career, you’ll come to learn the true value of a first impression. Allan and Barbara Pease also assert that when we meet people for the first time, we make snap judgments about their friendliness, assertiveness, and appearance. Without a single word being spoken, without even realizing it, people use nonverbal communication to size people up.

According to the 55/38/7 formula, nearly 40% of a person’s attitude is conveyed vocally through tone and inflection, so try to ensure that your tone matches whatever message you’re trying to convey. You can also try speaking in a deeper voice. Research has shown that people who speak with a low-pitched voice are rated more authoritative and competent than those who speak with a higher pitch.

Although people are rarely conscious of their body language and facial expressions, there are a couple of behaviors a person can tweak to improve their communication skills. For instance, research has shown that it takes conscious effort for a person to frown when looking at someone smiling—a smile is literally infectious. Research also shows that both men and women are more attracted to people who make eye contact and smile more often. A smile and just the right amount of eye contact can help you effectively convey information during first impressions and long after.

Hand gestures can not only express your thoughts but also convey your enthusiasm and passion for a topic. According to body language expert Dr. Carol Kinsey Goman, “Gesturing can help people form clearer thoughts, speak in tighter sentences and use more declarative language.” As with tone, try to ensure that your hand gestures match what you’re saying, otherwise people will notice the mismatch and may be less likely to trust you.

Interpreting Body Language
Body language can also provide insight into a person’s emotional condition. For example, you likely already know that someone who crosses their arms is guarded or discontent even when they claim the contrary. Reading body language is like learning a second language and can help separate perception from reality.

According to Dr. Jeff Thompson, we can better decipher nonverbal signals by remembering the three C’s of nonverbal communication: context, clusters, and congruence. We’ve already covered congruence—comparing spoken words to body language and tone. Applying context means better understanding the setting. For example, knowing that someone has anxiety can explain why they appear tense during a fireworks display. Finally, using clusters means using not one but multiple expressions or movements to influence our interpretation of a person’s body language. 

There’s So Much More to Communication
How much of communication is nonverbal? It may not be exactly 90%, but nonverbal communication—eye contact, smiling, hand gestures—heavily influences how people interpret and react to information. This is an important lesson to learn for anyone interested in a communications career, and it’s only the tip of the iceberg.
## Interpersonal

## Small-Group


## Public

## Mass Communication

## Intercultural






