---
  from: markdown+emoji  
---

::: {.callout-tip title="Quotes"}
::::{.flushright}
You only get one chance to make a first impression.\
[Oscar Wilde or Will Rogers]{.quoteauthor}
::::
:::

# Nonverbal Cues {#sec-nonverbal}

## Introduction

We introduced nonverbal communication as a form of communication in @sec-theory-nonverbal
as the ways in which we convey information by other means than speaking or
writing. The 7\% myth, namely that 93\% of communication is nonverbal, was debunked 
there. Whatever the true percentage, nonverbal communication is very important.
You can use it to your advantage and you can sabotage communication efforts
with it. The 93\% importance of nonverbal communication came from situations
where the nonverbal cues contradicted the verbal message. 

Nonverbal communication has multiple functions and effects. In his 
[teaching notes](https://www.andrews.edu/~tidwell/bsad560/NonVerbal.html) 
from Andrews University, Dean Emeritus Dr. Charles Tidwell lists

- To **repeat** the verbal message---pointing in a direction while stating directions
- To **accent** the verbal message---tone indicates the meaning
- To **complement** the verbal message---a nod reinforces a positive message, a
wink can contradict the verbal message
- To **regulate** interactions---conveying with hand gestures that a person should speak
- To **substitute** for the verbal message---raising fingers to lips to indicate quiet


Much of it is kind of obvious, for example, the effects of posture, body
language, gestures, eye contact, distance you keep, tone of voice, and so on.
It still takes awareness and practice to avoid nonverbal mistakes
and to draw on positive nonverbal cues to strengthen your communication.
Finally, pointing out elements of nonverbal communication, you become more aware
and tuned in, making it easier to read situations.

:::{.example}
::::{.example-header}
Example: The First Meeting
::::
::::{.example-container}
A client is meeting a statistical consultant in her office for the first time.
As the client enters, he notices a stack of papers on the chair in front of a 
massive desk, the statistician sits behind the desk, looking at her computer.
Without looking up from the computer she waves the client in, points at the chair,
and says "Hello, come on in. Take a seat."

The nonverbal cues and the setting convey that the consultant is not very interested
in the appointment or the consulting job. The fact that the chair intended for 
the client is used to store papers signals "don't get comfortable, don't stay
very long". Seating herself behind a large desk creates a barrier and puts the
client in an inferior position. Not making eye contact is another nonverbal 
cue that this meeting is not very important. 

Compare this to the setting where she has a small round conference table in her
office, shows the client in, gets up from behind her desk, walks toward the door,
looks at the client, points at the conference table, and greets them with 
"Hello, come on in. Take a seat." She waits for the client to be seated before
taking her seat.

The same greeting is used in both cases. And even if spoken with the same
enthusiasm, the nonverbal cues convey very different messages. In the second
setting the cues and the vocalization are completely aligned, creating a 
welcoming and respectful environment. In the second setting they are misaligned 
and the message conveyed by the verbal cues wins: I am busy and not very 
interested, do not have much time for you, don't stay too long; you and your 
project do not matter much to me.
::::
:::



It is easy to list what to do and what not to do with respect to nonverbal
communication, but changing things can be difficult or impossible. A behavior
can be due to an obsessive compulsive disorder. Maybe fidgeting or playing with
their hair is exactly what helps someone focus. It is easy to say "make eye contact",
it is much more difficult for an introvert than an extrovert. In trying to fix
a nonverbal cue you might overdo it and create the opposite effect; keeping
excessive eye contact is creepy and considered aggressive.

A Business Insider [article](https://www.businessinsider.com/horrible-body-language-habits-that-are-hard-to-quit-2016-10) 
from 2016 listed "9 horrible body language habits that are hard to quit", such as

- fidgeting
- playing with your hair
- adopting a defensive pose
- shuffling instead of walking
- forgetting to smile
- slouching
- nonexisting or aggressive eye contact

For starters, these should not be referred to as "horrible". We all do some of
these to varying degrees. I slouch and I slouch more when I am tired. There is
nothing wrong with shuffling while talking at times, it can be used to make a 
point about a slow-moving process. It can be a problem if that is the only way 
a speaker moves. The article was met with contemptuous comments such as 

:::{.quote}
wait you mean..stop being autistic? DIDNT KNOW I COULD DO THAT OH MY GOD!!!!!"
:::

The important thing is recognizing what can be improved, and working on that.
With so many poor communicators around, even small improvements can make you
stand out. Be yourself, but be the best version of yourself,

Whether a behavior can be changed or not, it is helpful to understand how cues
are typically interpreted and what signals they send.


:::{.callout-note title="Personal Experience"}
A good method to improve nonverbal cues by reinforcing positive and avoiding
negative nonverbal communication is to record oneself and watching it critically.
It is also a very painful method. Our voice sounds different in our own head, 
which is why recordings of ourselves sound strange. "Do I really sound like that?"

Seeing a video of yourself speaking is awkward and cringey. "Is that what
I sound and look like?". Well, yes, that is what we sound **and** look like. 

Before giving a speech, I would practice at home or in my office several times
without recording. Then I rehearse once or twice on a stage, recording video and
audio in front of people that would give me honest and constructive feedback.

The same issues would come up: too much pacing, hands folded in front of the
body (the "praying" posture), speaking too fast. I am still working on those
issues. But once aware, I can catch myself pacing or praying during a talk,
stand still, face the audience and show open palms.
:::

## Cultural Expectations

Nonverbal cues are particularly important in intercultural situations. The term
culture is interpreted very broadly here, the influences that shape a person's
expectations for communications. The different cultural interpretation of nonverbal cues 
is responsible for much mis-communication. What is acceptable or even expected
behavior in one culture can be offensive in another culture. For example, loudness 
of voice indicates strength in Arabic cultures, confidence and authority in Germany, 
impoliteness in Thailand, and loss of control to the Japanese.

The OK gesture (👌), performed by joining the thumb and index finger in a circle,
is frequently used as a sign of approval or assent, indicating something positive 
and well done. In Japan the sign is meant to represent a coin and indicates
wealth. In many other cultures the gesture has a negative and offensive 
connotation: it can represent a zero (or nothing of value), a vulgar expression
symbolizing the human anus (as in "you a**hole"), a homophobic reaction. 
The Anti-Defamation League added the OK gesture in 2019 to its "Hate on Display" 
database, as it has been used as an expression of white supremacy.

### Interpretations Vary

Here is a list of nonverbal cues with complicated cultural interpretations, 
based in part on [teaching notes](https://www.andrews.edu/~tidwell/bsad560/NonVerbal.html)
by Dr Charles Tidwell of Andrews University.

- **Posture**

    - Bowing: is not done in the U.S., shows respect and social rank in many 
    Asian cultures.
    - Hands in pocket: considered disrespectful in Turkey
    - Sitting with legs crossed: offensive in Turkey, Ghana
    - Showing soles of feet: a sign of disrespect in Arab, Muslim, Hindu, and 
    Buddhist countries
    
- **Facial Expressions**. Facial expressions that relate to anger, sorrow, sadness,
happiness have the same meaning world wide, but their intensity differs between
cultures. Too much smiling can be seen as a sign of shallowness. Many Asian 
cultures limit facial expressions. 

- **Eye Contact**. This one is tricky, because we are taught in Western cultures
that eye contact is generally a positive thing and we are aware that many communicators
do not make enough eye contact with their audience (looking at the floor, looking
at their slides, etc.). Across cultures direct and/or sustained eye contact is 
interpreted very differently.

    - Western cultures: eye contact is generally seen as positive, a sign of
    engagement and attentiveness. However, too much eye contact appears aggressive, 
    prolonged eye contact can be seen as a sign of sexual interest---no staring!
    - Arabic cultures: prolonged eye contact shows interest and establishes trust.
    Not reciprocating eye contact makes a person seen as not trustworthy.
    - In many Asian and Latin American cultures, avoiding eye contact or averting
    gaze is seen as a sign of respect.
    - In many East Asian cultures (Japan, Korea, China) direct eye contact is a 
    sign of disrespect, especially when speaking to someone of high(er) status.
    In Japanese culture, sustained eye contact is seen as a challenge or an 
    expression of dominance rather than a sign of engagement or attentiveness.
 
- **Touch**. Touch is culturally determined, the basic message when touching 
someone is to exercise control and to affect someone. The safe thing is not to 
have any physical contact when interacting with others. A handshake is a common
part of a greeting in Western cultures, but no-touch greetings or less-touch
greetings such as a fist bump are more acceptable. Expecting a handshake can 
be awkward when the other party does not reciprocate. For example, some 
interpretations of Islam and Judaism discourage or prohibit shaking hands with 
members of the opposite sex unless they are close relatives or spouses. 

If someone wants to greet you with a handshake and you'd rather not have
physical contact, it is fine to greet them with a nod and a smile.

---

@Derr2000 gives the following recommendations when meeting someone who might
have a different cultural background--and thus different nonverbal expectations:

- First impressions are nonverbal, and they have a cultural context
- Understand the expectations for your culture (typical greeting, eye contact,
inter-personal distance)
- Learn about the expectations in cultures you interact with professionally
- When possible, adopt your behavior to the audience's expectations
- If you get a negative first impression of someone, consider that their 
expectations for nonverbal communication might be different from yours
- Look out for discomfort in your audience, it will get in the way of the 
information you are trying to communicate

### Business Card Etiquette

Business cards are used less frequently today in the U.S., but they still play
a role when doing business across country borders. Especially in Asia, business
cards are important, considered an extension of the person. Mishandling a business
card is a sign of mishandling and disrespecting the person the card represents.

If you interact with Chinese, Korean, or Japanese professionally, you should know
the cultural expectations around business cards, especially if you are in a more
senior position as higher-ranking representatives exchange cards first. 

In China, Korea, and Japan, business cards should be in English on one side and
in the local language on the other side. Business cards are always kept in a 
special card case, never just stashed into a pocket. Receiving someone's card
and putting it in your back pocket is a major faux pas, you are signaling the  
person that you will be sitting on them soon.

Especially in Japan and Korea, the exchange of business cards is a ceremony.
Cards are exchanged on first meeting, both parties are standing up, facing 
each other. The presenter holds their card with **both** hands, facing toward the recipient 
with the translated side up. The exchange is accompanied by a bow and a vocal introduction 
of who you are and your job title. The recipient takes the card with both hands, 
**reads it**, and often comments on an aspect of the person as gleaned
from the card. This exchange takes time.

The recipient then places the card on the top of a card case or on the table in 
front of them when meeting around a conference table. The first card should be 
presented to the most senior staff member, working down the hierarchy after that.
Remember, the card is an extension of the person; how you treat the card is how 
you treat the person.
    
---


## Toastmaster World Champions

Before going through types of nonverbal cues, watch the following videos. These
are some of the the world champions in the annual Toastmaster competition. 
The presentations are short and excellent. Watch how the speakers use gesture, 
facial expression, body language, movement, pauses, tone of voice, softness and 
loudness, humor, audience engagement, to tell their story

:::{.centered}
{{< video https://www.youtube.com/watch?v=OpuMNgxRMac 
    title="Louisa Montalvo, 2024 World Champion"
    width="500" height="350" 
>}}

{{< video https://www.youtube.com/watch?v=bbz2boNSeL0
    title="Dananjaya Hettiarachchi, 2014 World Champion"
    width="500" height="350" 
>}}
:::

## Body Language {#sec-nonverbal-bodylanguage}

An **open** body language is inviting, calming, puts us at ease. This is a good
state of mind to receive information. A **defensive** body language signals
tension, resistance, and unease. An **aggressive** body language means I am 
coming for you, it triggers fight and flight response.

Elements of open body language are

- straight posture
- open arms
- showing palms of the hands
- smiling
- eyebrows open
- leaning forward
- making eye contact
- removing clothing (e.g. jacket, not all of it)

Defensive body language shows in

- crossed legs
- arms crossed in front of the chest
- avoiding eye contact
- hands in pockets
- clenched fists
- rigid body

Aggressive body language is seen in 

- clenched fists
- sneering
- tight muscles
- finger pointing
- hands on hips
- furrowed brow, eyebrows turned inwards
- pursed lips
- puffed chest
- blading (turning the body slightly away from a threat, as to protect vital organs)
- jaw thrust forward
- invading someone's space
- narrowing eyes


### Posture

### Gesture

### Facial Expressions

### Movement

## Voice

### Tone of Voice

### Filler Words

Common filler words in speech include "um", "ah", "er", "hmmm", like", "well", "so",
"right", "that", "well", "basically", "actually", "literally", "virtually", "yeah",
"practically", "seriously", I mean", "I guess", "I suppose", in fact","really", 
"sort of", "kind of", OK", "look", "anyway", "and stuff", and so on.

Charitably also known as *discourse markers*, filler words do not add any meaning 
but they are not entirely useless. Filler words can be used to provide space and 
thinking time for the speaker and the audience, they can indicate that the speaker 
is not yet finished, and make conversation seem less abrupt. A good-natured
hesitation before delivering bad news can indicate emotion.

When used excessively, filler words make the speaker sound unprepared and unsure, 
and they wear on the audience. They distract from the other words in your message.
The audience has to filter them out of the message to get to the meaning.

And then there are particularly grating filler phrases, made up of collections
of filler words: "and so on and so forth", "at the end of the day", "to be honest",
"to tell you the truth", "you know what", "you know what I'm saying", and so 
on and so forth.

Filler words often come out unconsciously, which makes them difficult to, you know,
basically stop. When writing, re-read sentences looking for words that
can be deleted without altering the meaning. Compare the following pairs of
sentences:

>I just hit a deer. \
I hit a deer.

> Can you just send me the file?\
Can you send me the file?

In the first case *just* anchors the event in time, the deer was hit recently.
It is not a filler word. In the second case *just* can be removed without 
altering the meaning, you are asking for the file to be sent. It is a filler 
word in that case.

When speaking, here are some hints to avoid or reduce the use of filler words:

* Slow down. Using filler words might be caused by speaking too fast. You then
insert filler words to give yourself time to catch up to the spoken words. Slowing
down speech gives you more time to think and makes the conversation more relaxed.

* Embrace the silence. We use filler words to avoid silence and pauses in speech.
Silence does not have to be awkward, it can lend emphasis and draw the audience
in. If you are not sure what to say next, do not say anything at all. Keep calm
and soldier on. 

* Negative Practice. Overdo the very thing you want to avoid doing. For example, if 
you tend to use "like" as a filler word, make a conscious effort to use "like"
10 times in each sentence. By practicing what you want to avoid, you are moving
the habit from the subconscious mind to the conscious mind.
And now you can address it by replacing the word "like" with a short pause.

* Record yourself. Play back the recording and count filler words. We all use
them more than we think we are.

:::{.centered}

{{< video https://www.youtube.com/watch?v=OrNCkiYvWhg >}}

:::


## Other Communication Channels

Nonverbal communication also plays an important role when you cannot see
the person you are communicating with. Text messages and email, for example, are 
forms of verbal communication because you type out words. They also have
nonverbal cues such as emojis, punctuation, capitalization, slang, response 
length and time. A quick reply can suggest enthusiasm, long response times can
indicate disinterest. Use of periods, question marks, and exclamation points can 
add clarity to the message and indicate tone and emphasis. Emojis are a substitute
for facial expressions and body language, allowing the sender to express emotion.

Tone of voice, pitch, volume, inflection, pace of speech, breathing, silences are 
called **paralinguisitics** and are the nonverbal cues you can use when speaking
to someone you cannot see. When phones first became more widely available, 
phone courtesy was lacking. People were not used to speaking without seeing the
other person. Employees berated their bosses on the phone because the typical 
cues that established hierarchy (office, desk, suit, appearance) and conditioned 
behavior were not visible. 

The following nonverbal cues affect phone communication:

- A calm and friendly voice creates a sense of trust and professionalism.
- Do not speak too fast, normal rate of speech is about 125 words per minute.
- Strategic silences allow the other person to process information, but prolonged
silences create awkwardness.
- Active listening can be shown with phrases such as "mm-hmm" or "I understand".
- Although the recipient cannot see you smile, smiling while speaking influences
your tone of voice, you sound more friendly. Siting upright or standing also
affects your tone of voice.






